# Generated by Django 5.1.6 on 2025-03-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restore_password_verification',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='код верификации email'),
        ),
    ]
