# Generated by Django 5.1.4 on 2025-02-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='clients',
            field=models.ManyToManyField(related_name='all_clients', to='distribution.client', verbose_name='клиенты рассылки'),
        ),
    ]
