# Generated by Django 5.1.6 on 2025-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_mailingsettings_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активность рассылки'),
        ),
    ]
