# Generated by Django 5.1.6 on 2025-02-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_mailingsettings_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='client',
        ),
        migrations.AddField(
            model_name='log',
            name='recipient_list',
            field=models.TextField(blank=True, null=True, verbose_name='список получателей'),
        ),
    ]
