# Generated by Django 5.1.6 on 2025-03-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_client_owner_log_owner_mailingsettings_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('FIO',), 'permissions': [('can_see_all_clients', 'Can see all clients')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'permissions': [('can_see_all_logs', 'Can see all logs')], 'verbose_name': 'лог', 'verbose_name_plural': 'логи'},
        ),
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('can_see_all_mailing_settings', 'Can see all mailing settings')], 'verbose_name': 'настройки рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_see_all_messages', 'Can see all messages')], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
