# Generated by Django 5.1.6 on 2025-03-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_alter_client_options_alter_log_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='почта'),
        ),
    ]
