# Generated by Django 5.1.6 on 2025-03-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_alter_client_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('can_see_all_clients', 'Can see all clients')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('can_see_all_mailing_settings', 'Can see all mailing settings')], 'verbose_name': 'настройки рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_see_all_messages', 'Can see all messages')], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.RemoveField(
            model_name='log',
            name='recipient_list',
        ),
        migrations.AddField(
            model_name='log',
            name='recipient',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email получателя'),
        ),
    ]
